language: node_js

cache: yarn

jobs:
  include:
    - stage: release
      deploy:
        provider: script
        on:
          branch: master
        skip_cleanup: true
        script:
          - npx semantic-release
