language: node_js

cache: yarn

jobs:
  include:
    - stage: release
      deploy:
        provider: script
        on:
          all_branches: true
        skip_cleanup: true
        script:
          - npx semantic-release
