language: node_js

node_js:
  - 10.15.3

cache: yarn

jobs:
  include:
    - stage: release
      node_js: 10.15.3
      deploy:
        provider: script
        on:
          branch: master
        skip_cleanup: true
        script:
          - npx semantic-release
      deploy:
        provider: script
        on:
          branch: alpha
        skip_cleanup: true
        script:
          - npx semantic-release
